version: "2.0"
services:
  bot:
    tty: true
    build: "src"
    env_file: ./.env
    mem_limit: 4g
  voicevox-engine:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "50021:50021"
